In [5]:
import numpy as np

## DataTypes & Attributes

In [6]:
#NumPy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [7]:
type(a1)

numpy.ndarray

In [8]:
a2 = np.array([[1,2.0,3.3],
               [4,5,6.5]])

a3 = np.array([
               [[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]
              ])

In [9]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
a1.shape

(3,)

In [12]:
a2.shape

(2, 3)

In [13]:
a3.shape

(2, 3, 3)

In [14]:
a1.ndim

1

In [15]:
a2.ndim

2

In [16]:
a3.ndim

3

In [17]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [18]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [19]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [20]:
# Create a DataFrame from a Numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [21]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [22]:
sample_array.dtype

dtype('int32')

In [26]:
ones = np.ones((2,3))

In [27]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
ones.dtype

dtype('float64')

In [29]:
type(ones)

numpy.ndarray

In [30]:
zeros = np.zeros((2,3))

In [31]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
range_array = np.arange(0, 10, 2)

In [35]:
range_array

array([0, 2, 4, 6, 8])

In [38]:
random_array = np.random.randint(0, 10, size=(3,5))

In [39]:
random_array

array([[6, 3, 4, 8, 1],
       [4, 2, 1, 8, 7],
       [3, 9, 8, 5, 9]])

In [41]:
random_array.size

15

In [42]:
random_array.shape

(3, 5)

In [43]:
random_array2 = np.random.random((5,3))
random_array2

array([[0.75981905, 0.78483736, 0.50432706],
       [0.73779703, 0.55513142, 0.41739372],
       [0.78199726, 0.79344776, 0.47172084],
       [0.72877896, 0.75648587, 0.12625644],
       [0.93175725, 0.08850733, 0.74458308]])

In [44]:
random_array2.shape

(5, 3)

In [45]:
random_array3 = np.random.rand(5,3)
random_array3

array([[0.9113052 , 0.43287325, 0.32505484],
       [0.72721888, 0.60958932, 0.74677125],
       [0.13995234, 0.59799182, 0.95104403],
       [0.54630851, 0.72733364, 0.22300861],
       [0.49109684, 0.08425796, 0.45895952]])

In [58]:
# Pseudo-random numbers
np.random.seed(seed=99999)
random_array4 = np.random.randint(10, size=(5,3))
random_array4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [51]:
random_array4.shape

(5, 3)

In [60]:
np.random.seed(7)
random_array5 = np.random.random((5,3))
random_array5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [61]:
random_array5 = np.random.random((5,3))
random_array5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])