#### 1.Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`

In [1]:
import tensorflow as tf

In [2]:
import numpy as np

In [9]:
scalar =  tf.constant(3)
scalar, scalar.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=3>, 0)

In [10]:
vector = tf.constant([1,2])
vector, vector.ndim


(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>, 1)

In [11]:
matrix = tf.constant([[1,2],[2,3]])
matrix, matrix.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [2, 3]], dtype=int32)>,
 2)

In [13]:
tensor = tf.constant([[[1,2],[3,4]],
                      [[5,6],[7,8]]])
tensor, tensor.ndim

(<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
 array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]], dtype=int32)>,
 3)

#### 2.Find the shape, rank and size of the tensor created

In [15]:
tensor.shape, tf.size(tensor), tf.rank(tensor)

(TensorShape([2, 2, 2]),
 <tf.Tensor: shape=(), dtype=int32, numpy=8>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>)

#### 3.Create two tenors containing random values between 0 and 1 with shape [5,300].


In [20]:
random_tensor1 = tf.random.uniform(shape=(5,300))
random_tensor1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.05987561, 0.82498634, 0.22176504, ..., 0.32132864, 0.25710905,
        0.00912929],
       [0.5548352 , 0.31122017, 0.99403465, ..., 0.396762  , 0.38572717,
        0.3406794 ],
       [0.10606539, 0.57817173, 0.31108224, ..., 0.17935681, 0.795966  ,
        0.4910493 ],
       [0.55464363, 0.38794434, 0.31176722, ..., 0.56971383, 0.633031  ,
        0.17668283],
       [0.14683366, 0.4476596 , 0.39020562, ..., 0.6953801 , 0.73447835,
        0.45172656]], dtype=float32)>

In [21]:
random_tensor2 = tf.random.uniform(shape=(5,300))
random_tensor2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.2777418 , 0.8119087 , 0.41244888, ..., 0.22146583, 0.39385772,
        0.24781835],
       [0.07551348, 0.02744889, 0.48361826, ..., 0.7783413 , 0.17756498,
        0.38000977],
       [0.23571432, 0.310238  , 0.20518768, ..., 0.2680478 , 0.74562204,
        0.59642863],
       [0.7855916 , 0.15216494, 0.45203698, ..., 0.60495985, 0.7927376 ,
        0.05976522],
       [0.44285238, 0.11362851, 0.28142536, ..., 0.18795717, 0.30841708,
        0.8339578 ]], dtype=float32)>

#### 4.Multiply the two tensors you created in 3 using matrix multiplication.

In [23]:
tf.linalg.matmul(random_tensor1, random_tensor2,  transpose_b=True)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[76.670395, 71.13551 , 71.35396 , 76.73754 , 75.32904 ],
       [72.780594, 70.98184 , 69.866104, 74.88263 , 72.99069 ],
       [73.53587 , 65.23196 , 67.88296 , 70.02713 , 70.28499 ],
       [76.398796, 69.07962 , 70.35627 , 76.05353 , 74.12025 ],
       [70.994514, 66.11299 , 67.18524 , 73.50718 , 70.89786 ]],
      dtype=float32)>

#### 5.Multiply the two tensors you created using dot product.

In [27]:
tf.tensordot(random_tensor1, tf.transpose(random_tensor2), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[76.670395, 71.13551 , 71.35396 , 76.73754 , 75.32904 ],
       [72.780594, 70.98184 , 69.866104, 74.88263 , 72.99069 ],
       [73.53587 , 65.23196 , 67.88296 , 70.02713 , 70.28499 ],
       [76.398796, 69.07962 , 70.35627 , 76.05353 , 74.12025 ],
       [70.994514, 66.11299 , 67.18524 , 73.50718 , 70.89786 ]],
      dtype=float32)>

#### 6.Create a tensor with random values between 0 and 1 with shape [224,224,3]


In [31]:
random_tensor3 = tf.random.uniform(shape=(224,224,3))
random_tensor3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.27045   , 0.28439677, 0.67773926],
        [0.60243845, 0.29166102, 0.32092702],
        [0.45362675, 0.60064924, 0.1492306 ],
        ...,
        [0.95068574, 0.9535047 , 0.17050743],
        [0.6224586 , 0.7088213 , 0.18155491],
        [0.7075523 , 0.9301311 , 0.89720523]],

       [[0.13407207, 0.21994627, 0.59090054],
        [0.29772258, 0.8362398 , 0.02416408],
        [0.72123575, 0.7791623 , 0.6785729 ],
        ...,
        [0.16221881, 0.6444409 , 0.62161684],
        [0.91668224, 0.5273088 , 0.99014604],
        [0.32197416, 0.11072707, 0.47903287]],

       [[0.40876818, 0.9523548 , 0.8609592 ],
        [0.02770197, 0.5414518 , 0.76117706],
        [0.40923357, 0.62166643, 0.22260368],
        ...,
        [0.14192641, 0.8304596 , 0.89919496],
        [0.5464338 , 0.541957  , 0.7938585 ],
        [0.9611287 , 0.07247841, 0.2604133 ]],

       ...,

       [[0.47305274, 0.72428656, 0.9097792 ],
        [0.36

#### 7.Find the min and max values of the tensor you created in 6 along the first axis.

In [35]:
tf.reduce_max(random_tensor3), tf.reduce_min(random_tensor3)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.99999976>,
 <tf.Tensor: shape=(), dtype=float32, numpy=5.6028366e-06>)

#### 8. Create a tensor with random values of shape [1,224,224,3] then squeeze it to change the shape to [224,224,3]

In [39]:
big_tensor = tf.random.uniform(shape=[1,224,224,3])
big_tensor

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.5047873 , 0.9172604 , 0.19664097],
         [0.23699951, 0.6490557 , 0.48869765],
         [0.4998803 , 0.718869  , 0.981406  ],
         ...,
         [0.04157698, 0.98003495, 0.14617121],
         [0.6075721 , 0.11199212, 0.9289863 ],
         [0.6717515 , 0.4586885 , 0.16492689]],

        [[0.48897457, 0.7653477 , 0.36601877],
         [0.09907985, 0.22704148, 0.20799196],
         [0.49821413, 0.68127716, 0.7235756 ],
         ...,
         [0.53412044, 0.56030595, 0.8828156 ],
         [0.48528528, 0.7559923 , 0.01413321],
         [0.7815219 , 0.1596905 , 0.00956225]],

        [[0.0472194 , 0.362813  , 0.8427174 ],
         [0.54395604, 0.49633932, 0.817271  ],
         [0.89737666, 0.22024977, 0.8185973 ],
         ...,
         [0.98013055, 0.71873784, 0.75347364],
         [0.87099886, 0.9569268 , 0.67975664],
         [0.31493318, 0.21248531, 0.02520895]],

        ...,

        [[0.6880467 , 0.50866103, 

In [42]:
squeeze_tensor = tf.squeeze(big_tensor)
squeeze_tensor, squeeze_tensor.shape

(<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
 array([[[0.5047873 , 0.9172604 , 0.19664097],
         [0.23699951, 0.6490557 , 0.48869765],
         [0.4998803 , 0.718869  , 0.981406  ],
         ...,
         [0.04157698, 0.98003495, 0.14617121],
         [0.6075721 , 0.11199212, 0.9289863 ],
         [0.6717515 , 0.4586885 , 0.16492689]],
 
        [[0.48897457, 0.7653477 , 0.36601877],
         [0.09907985, 0.22704148, 0.20799196],
         [0.49821413, 0.68127716, 0.7235756 ],
         ...,
         [0.53412044, 0.56030595, 0.8828156 ],
         [0.48528528, 0.7559923 , 0.01413321],
         [0.7815219 , 0.1596905 , 0.00956225]],
 
        [[0.0472194 , 0.362813  , 0.8427174 ],
         [0.54395604, 0.49633932, 0.817271  ],
         [0.89737666, 0.22024977, 0.8185973 ],
         ...,
         [0.98013055, 0.71873784, 0.75347364],
         [0.87099886, 0.9569268 , 0.67975664],
         [0.31493318, 0.21248531, 0.02520895]],
 
        ...,
 
        [[0.6880467 , 0.50866103

#### 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value

In [47]:
tensor10 = tf.constant([1,2,3,4,5,6,7,8,9,10])

In [48]:
tensor10.shape

TensorShape([10])

In [55]:
index_max = tf.argmax(tensor10).numpy()

In [56]:
max_value = tf.reduce_max(tensor10).numpy()

In [58]:
print(f"The max value is: {max_value}\n")
print(f"The index of the max value is: {index_max}\n")

The max value is: 10

The index of the max value is: 9



#### 10.One-hot encode the tensor you created in 9.

In [65]:
tf.cast(tensor10, dtype=tf.int32)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)>

In [66]:
tf.one_hot(tf.cast(tensor10, dtype=tf.int32), depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>